name = "see-you-there-service"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-04"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"                         # available in your Worker on env.DB
database_name = "met-you-there-db"
database_id = "afeafeuiafnwe8247r2qjf"
