name = "see-you-there-service"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-04"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"                                       # available in your Worker on env.DB
database_name = "syt-ts"
database_id = "4ec758c4-921e-44c2-83ea-261bc9345484"
